<?php
// $Id

/**
 * @file
 * Drupal hooks
 *
 * @author Davy Van Den Bremt
 */

/**
 * Implementation of hook_menu().
 */
function mailchimp_menu() {

  // settings
  $items['admin/settings/mailchimp'] = array(
    'title' => 'MailChimp',
    'description' => 'Configure MailChimp settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mailchimp.settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_emf_info().
 */
function mailchimp_emf_info() {
  return array(
    'name' => 'MailChimp',
    'file' => 'mailchimp.api.inc',
  );
}